function word(en, zh, partOfSpeech, defEn, synonym, example, zhAliases = []) {
  return { en, zh, partOfSpeech, defEn, synonym, example, zhAliases };
}

const easyWords = [
  word("apple", "苹果", "名词", "A round fruit with red or green skin.", "fruit", "She eats an apple every day.", ["苹果果", "苹果儿"]),
  word("book", "书", "名词", "A set of written or printed pages.", "volume", "This book is very interesting.", ["书本", "书籍"]),
  word("water", "水", "名词", "A clear liquid used for drinking.", "H2O", "Drink more water after exercise.", ["饮用水"]),
  word("school", "学校", "名词", "A place where students learn.", "campus", "He walks to school every morning.", ["校园"]),
  word("family", "家庭", "名词", "People related to each other.", "relatives", "Family support is important.", ["家人"]),
  word("happy", "开心的", "形容词", "Feeling or showing pleasure.", "glad", "The children look happy.", ["开心", "高兴", "高兴的"]),
  word("friend", "朋友", "名词", "A person you like and trust.", "companion", "My friend helps me with homework.", ["伙伴", "好友"]),
  word("sun", "太阳", "名词", "The star that gives Earth light and heat.", "daystar", "The sun is bright today.", ["太阳光", "日头"]),
  word("music", "音乐", "名词", "Pleasant sounds made with voice or instruments.", "melody", "She listens to music while reading.", ["乐曲", "乐声"]),
  word("garden", "花园", "名词", "An area where flowers or plants are grown.", "yard", "We planted roses in the garden.", ["园子", "庭院"]),
  word("dog", "狗", "名词", "An animal often kept as a pet.", "puppy", "The dog runs across the yard.", ["小狗", "狗狗"]),
  word("cat", "猫", "名词", "A small animal with soft fur.", "kitten", "The cat is sleeping on the chair.", ["小猫", "猫咪"]),
  word("house", "房子", "名词", "A building where people live.", "home", "Their house is near the river.", ["房屋", "住宅"]),
  word("car", "汽车", "名词", "A road vehicle with an engine.", "vehicle", "My father drives a car to work.", ["小汽车", "车子"]),
  word("food", "食物", "名词", "Things that people or animals eat.", "meal", "Healthy food gives us energy.", ["食品", "吃的"]),
  word("table", "桌子", "名词", "A piece of furniture with a flat top.", "desk", "The cups are on the table.", ["桌", "餐桌"]),
  word("chair", "椅子", "名词", "A seat for one person.", "seat", "Please sit on the chair.", ["座椅"]),
  word("teacher", "老师", "名词", "A person who teaches students.", "educator", "The teacher explains the question clearly.", ["教师"]),
  word("student", "学生", "名词", "A person who is learning at school.", "learner", "Every student needs enough sleep.", ["学员"]),
  word("breakfast", "早餐", "名词", "The first meal of the day.", "morning meal", "I usually eat bread for breakfast.", ["早饭"]),
  word("lunch", "午餐", "名词", "A meal eaten in the middle of the day.", "midday meal", "We have lunch at twelve o'clock.", ["午饭"]),
  word("dinner", "晚餐", "名词", "The main meal eaten in the evening.", "evening meal", "The family cooks dinner together.", ["晚饭"]),
  word("small", "小的", "形容词", "Little in size.", "tiny", "The box is too small for the toy.", ["小", "较小的"]),
  word("big", "大的", "形容词", "Large in size.", "large", "They live in a big house.", ["大", "很大的"]),
  word("clean", "干净的", "形容词", "Not dirty.", "neat", "The room looks clean now.", ["干净", "整洁的"]),
  word("busy", "忙碌的", "形容词", "Having a lot to do.", "occupied", "She is busy with her homework.", ["忙的", "繁忙的"]),
  word("morning", "早晨", "名词", "The early part of the day.", "dawn", "I like running in the morning.", ["早上", "清晨"]),
  word("night", "夜晚", "名词", "The time when it is dark.", "evening", "The stars shine at night.", ["夜里", "晚上"]),
  word("read", "阅读", "动词", "To look at and understand written words.", "study", "Children read storybooks before bed.", ["读", "朗读"]),
  word("write", "写", "动词", "To make letters or words on paper.", "record", "Please write your name here.", ["书写", "写下"]),
  word("window", "窗户", "名词", "An opening in a wall that lets in light.", "pane", "Please open the window for fresh air.", ["窗子"]),
  word("door", "门", "名词", "A movable barrier used to open or close an entrance.", "gate", "He knocked on the front door.", ["房门", "门口的门"]),
  word("flower", "花", "名词", "The colorful part of a plant.", "blossom", "This flower smells sweet.", ["花朵"]),
  word("river", "河流", "名词", "A natural stream of water.", "stream", "A river runs behind the village.", ["河", "小河"]),
  word("mountain", "山", "名词", "A very high area of land.", "peak", "Snow covers the mountain in winter.", ["山峰"]),
  word("road", "道路", "名词", "A way for cars, bikes, or people to travel on.", "street", "The road is busy after work.", ["马路", "路"]),
  word("bike", "自行车", "名词", "A vehicle with two wheels that you ride.", "bicycle", "She rides her bike to school.", ["单车", "脚踏车"]),
  word("bus", "公共汽车", "名词", "A large road vehicle for many passengers.", "coach", "We take the bus downtown.", ["公交车", "巴士"]),
  word("train", "火车", "名词", "A line of connected railway cars.", "railway", "The train arrives at six.", ["列车"]),
  word("computer", "电脑", "名词", "An electronic machine that stores and processes data.", "PC", "He uses the computer for homework.", ["计算机"]),
  word("phone", "电话", "名词", "A device used to talk to someone far away.", "telephone", "I forgot my phone at home.", ["手机", "电话号码的电话"]),
  word("clothes", "衣服", "名词", "Things people wear on their bodies.", "clothing", "These clothes are warm and soft.", ["服装"]),
  word("fruit", "水果", "名词", "Sweet food that grows on trees or plants.", "produce", "Fresh fruit is good for health.", ["果子"]),
  word("milk", "牛奶", "名词", "A white liquid drink from cows.", "dairy", "Warm milk helps me sleep.", ["奶"]),
  word("bread", "面包", "名词", "Food made from flour and baked.", "loaf", "She bought bread from the bakery.", ["面包片"]),
  word("picture", "图片", "名词", "A drawing or photograph.", "image", "The picture on the wall is beautiful.", ["照片", "图画"]),
  word("weather", "天气", "名词", "The condition of the air outside.", "climate", "The weather is nice today.", ["气候"]),
  word("smile", "微笑", "名词", "A happy expression on the face.", "grin", "Her smile made everyone relax.", ["笑容"]),
  word("answer", "答案", "名词", "Something said or written in reply.", "reply", "I know the answer to this question.", ["回答"]),
  word("question", "问题", "名词", "Something you ask when you want information.", "query", "The teacher asked an easy question.", ["题目", "疑问"])
];

const mediumWords = [
  word("improve", "提升", "动词", "To make something better.", "enhance", "Practice can improve your English.", ["提高", "改进"]),
  word("create", "创造", "动词", "To make something new.", "produce", "Students create a small robot.", ["创建", "创作"]),
  word("travel", "旅行", "动词", "To go from one place to another.", "journey", "They travel by train in summer.", ["旅游", "出行"]),
  word("future", "未来", "名词", "The time that is yet to come.", "prospect", "She plans for her future carefully.", ["将来"]),
  word("energy", "能量", "名词", "Power needed for physical activity.", "power", "Healthy food gives us energy.", ["精力", "力量"]),
  word("memory", "记忆", "名词", "The ability to remember things.", "recollection", "This song brings back old memory.", ["回忆"]),
  word("culture", "文化", "名词", "Ideas and customs of a society.", "civilization", "Food is part of local culture.", ["文明", "文化传统"]),
  word("honest", "诚实的", "形容词", "Telling the truth and not cheating.", "truthful", "An honest answer is always best.", ["诚实", "老实", "老实的"]),
  word("protect", "保护", "动词", "To keep safe from harm.", "guard", "Trees protect the soil from rain.", ["保卫", "守护"]),
  word("discover", "发现", "动词", "To find something for the first time.", "find", "Scientists discover new stars.", ["发觉", "察觉"]),
  word("develop", "发展", "动词", "To grow or change over time.", "grow", "The city continues to develop quickly.", ["成长", "进步"]),
  word("support", "支持", "动词", "To help or agree with someone or something.", "assist", "Parents support their children warmly.", ["帮助", "支撑"]),
  word("prepare", "准备", "动词", "To get ready for something.", "get ready", "We prepare for the exam together.", ["预备", "筹备"]),
  word("compare", "比较", "动词", "To examine how things are similar or different.", "contrast", "Let's compare the two plans.", ["对比"]),
  word("decide", "决定", "动词", "To make a choice.", "determine", "She decides to join the club.", ["下决定", "作出决定"]),
  word("possible", "可能的", "形容词", "Able to happen or exist.", "likely", "Anything is possible with effort.", ["可能", "有可能的"]),
  word("careful", "仔细的", "形容词", "Giving attention to detail.", "cautious", "Be careful when crossing the street.", ["仔细", "小心的"]),
  word("special", "特别的", "形容词", "Different from others in a good way.", "unique", "Today is a special day for us.", ["特殊的", "特别"]),
  word("important", "重要的", "形容词", "Having great value or effect.", "key", "Sleep is important for students.", ["关键的", "重要"]),
  word("popular", "受欢迎的", "形容词", "Liked by many people.", "well-liked", "That singer is popular among teens.", ["热门的", "流行的"]),
  word("practice", "练习", "名词", "Repeated work to improve a skill.", "training", "Daily practice makes pronunciation better.", ["训练"]),
  word("conversation", "对话", "名词", "A talk between two or more people.", "talk", "Their conversation lasted an hour.", ["交谈"]),
  word("knowledge", "知识", "名词", "Information and understanding gained by learning.", "understanding", "Reading adds to our knowledge.", ["学识"]),
  word("environment", "环境", "名词", "The natural world or surroundings.", "surroundings", "We should care for the environment.", ["周围环境"]),
  word("information", "信息", "名词", "Facts or details about something.", "data", "The poster gives useful information.", ["资讯"]),
  word("opportunity", "机会", "名词", "A good chance to do something.", "chance", "This job offers a great opportunity.", ["机遇"]),
  word("experience", "经历", "名词", "Knowledge or skill gained over time.", "undergoing", "Travel is a valuable experience.", ["体验", "经验"]),
  word("include", "包括", "动词", "To have something as part of a whole.", "contain", "The price includes breakfast.", ["包含"]),
  word("achieve", "实现", "动词", "To succeed in doing something.", "accomplish", "You can achieve your goal step by step.", ["达成", "取得"]),
  word("reduce", "减少", "动词", "To make something smaller or less.", "decrease", "We should reduce waste at home.", ["降低", "缩减"]),
  word("relationship", "关系", "名词", "The way two or more people or things are connected.", "connection", "Trust is important in every relationship.", ["联系"]),
  word("method", "方法", "名词", "A particular way of doing something.", "approach", "This method saves a lot of time.", ["办法"]),
  word("communicate", "沟通", "动词", "To share information with others.", "interact", "Good leaders communicate clearly.", ["交流"]),
  word("prefer", "更喜欢", "动词", "To like one thing more than another.", "favor", "I prefer tea to coffee.", ["偏爱", "更偏向"]),
  word("manage", "管理", "动词", "To control or deal with something successfully.", "handle", "She can manage the team well.", ["处理", "设法做到"]),
  word("increase", "增加", "动词", "To become greater in amount or size.", "rise", "Exercise can increase your strength.", ["提升", "增多"]),
  word("solve", "解决", "动词", "To find an answer to a problem.", "fix", "We need to solve this issue today.", ["处理", "搞定"]),
  word("local", "当地的", "形容词", "Belonging to a particular area nearby.", "regional", "We visited a local market.", ["本地的", "当地"]),
  word("tradition", "传统", "名词", "A belief or custom passed down over time.", "custom", "This festival is an old tradition.", ["习俗"]),
  word("education", "教育", "名词", "The process of teaching and learning.", "schooling", "Education changes people's lives.", ["教学"]),
  word("article", "文章", "名词", "A piece of writing in a newspaper or magazine.", "essay", "She wrote an article about health.", ["报道"]),
  word("research", "研究", "名词", "Careful study to discover new facts.", "study", "The team began research on climate.", ["调查"]),
  word("emotion", "情绪", "名词", "A strong feeling such as joy or sadness.", "feeling", "Music can affect our emotion.", ["情感", "感情"]),
  word("habit", "习惯", "名词", "Something you do often and regularly.", "routine", "Reading before bed is a good habit.", ["习性"]),
  word("quality", "质量", "名词", "How good something is.", "standard", "We care about product quality.", ["品质"]),
  word("response", "回应", "名词", "A spoken or written answer.", "reaction", "His response was quick and polite.", ["反应", "答复"]),
  word("topic", "话题", "名词", "A subject people talk or write about.", "subject", "Climate change is an important topic.", ["主题"]),
  word("focus", "专注", "名词", "Special attention given to something.", "attention", "Today's focus is listening practice.", ["集中", "关注点"])
];

const hardWords = [
  word("consequence", "后果", "名词", "A result of an action or condition.", "outcome", "Ignoring warnings has serious consequence.", ["结果"]),
  word("efficient", "高效的", "形容词", "Working well without wasting time.", "productive", "A clear plan makes work more efficient.", ["高效", "效率高", "有效率的"]),
  word("significant", "重要的", "形容词", "Large or important enough to be noticed.", "meaningful", "There is significant progress this week.", ["显著的", "重大的", "重要"]),
  word("perspective", "视角", "名词", "A way of thinking about something.", "viewpoint", "Try to see it from another perspective.", ["角度", "观点"]),
  word("collaborate", "合作", "动词", "To work together with others.", "cooperate", "Teams collaborate to solve hard problems.", ["协作", "配合"]),
  word("motivation", "动力", "名词", "The reason to do something.", "drive", "Progress gives students motivation.", ["驱动力", "积极性"]),
  word("challenge", "挑战", "名词", "A difficult task that tests ability.", "test", "Every level brings a new challenge.", ["难题", "考验"]),
  word("strategy", "策略", "名词", "A detailed plan for success.", "plan", "Our strategy improved the final score.", ["战略", "方案"]),
  word("resource", "资源", "名词", "A supply that can be used.", "asset", "Time is your most valuable resource.", ["物资", "资源条件"]),
  word("resilient", "有韧性的", "形容词", "Able to recover quickly from difficulty.", "tough", "Resilient learners keep trying.", ["有韧性", "坚韧", "坚韧的"]),
  word("analyze", "分析", "动词", "To study something carefully.", "examine", "Scientists analyze the results in detail.", ["解析"]),
  word("maintain", "维持", "动词", "To keep something in good condition.", "preserve", "It is hard to maintain balance at first.", ["保持", "维护"]),
  word("adapt", "适应", "动词", "To change in order to fit a new situation.", "adjust", "Good teams adapt to sudden change.", ["调整以适应", "适应变化"]),
  word("complex", "复杂的", "形容词", "Having many connected parts.", "complicated", "The problem is more complex than it looks.", ["复杂", "繁杂的"]),
  word("accurate", "准确的", "形容词", "Correct and exact.", "precise", "An accurate translation is important.", ["准确", "精确的"]),
  word("flexible", "灵活的", "形容词", "Able to change easily when needed.", "adaptable", "A flexible plan is often safer.", ["灵活", "有弹性的"]),
  word("innovative", "创新的", "形容词", "Using new ideas or methods.", "creative", "The company is known for innovative design.", ["创新", "有创新性的"]),
  word("sustainable", "可持续的", "形容词", "Able to continue for a long time.", "lasting", "We need sustainable ways to save energy.", ["可持续", "持续发展的"]),
  word("essential", "必不可少的", "形容词", "Completely necessary.", "necessary", "Rest is essential for good performance.", ["必要的", "关键的", "不可或缺的"]),
  word("interpret", "解释", "动词", "To explain the meaning of something.", "explain", "Different people interpret the poem differently.", ["解读", "诠释"]),
  word("evaluate", "评估", "动词", "To judge the value or quality of something.", "assess", "Teachers evaluate each project fairly.", ["评价", "考量"]),
  word("implement", "实施", "动词", "To put a plan into action.", "carry out", "The team will implement the new system soon.", ["执行", "落实"]),
  word("allocate", "分配", "动词", "To give different parts of something to different uses.", "assign", "We must allocate time wisely.", ["分派", "调配"]),
  word("negotiate", "协商", "动词", "To discuss in order to reach an agreement.", "discuss", "The two sides negotiate a final price.", ["谈判", "商议"]),
  word("priority", "优先事项", "名词", "Something that is more important than other things.", "main concern", "Safety should be our top priority.", ["优先级", "首要事项"]),
  word("assumption", "假设", "名词", "Something accepted as true without proof.", "belief", "That assumption may be wrong.", ["设想", "假说"]),
  word("framework", "框架", "名词", "A basic structure or system.", "structure", "This framework helps us organize ideas.", ["结构", "体系"]),
  word("clarify", "澄清", "动词", "To make something easier to understand.", "make clear", "Please clarify the last point again.", ["说明清楚", "阐明"]),
  word("consistent", "一致的", "形容词", "Always behaving in the same way.", "steady", "Consistent effort leads to progress.", ["稳定的", "前后一致的"]),
  word("transform", "转变", "动词", "To change something greatly.", "change", "Technology can transform daily life.", ["改变", "转化"]),
  word("concept", "概念", "名词", "An abstract idea or general notion.", "idea", "The concept sounds simple but is powerful.", ["观念"]),
  word("phenomenon", "现象", "名词", "A fact or event that can be observed.", "occurrence", "Rainbows are a natural phenomenon.", ["现象表现"]),
  word("diverse", "多样的", "形容词", "Showing a great deal of variety.", "varied", "The city has a diverse culture.", ["多元的", "丰富多样的"]),
  word("establish", "建立", "动词", "To start or set up something firmly.", "found", "They want to establish clear rules.", ["创立", "设立"]),
  word("intervene", "干预", "动词", "To become involved in a situation to change it.", "step in", "Teachers may intervene when problems grow.", ["介入"]),
  word("inevitable", "不可避免的", "形容词", "Certain to happen and impossible to avoid.", "unavoidable", "Some change is inevitable.", ["必然的", "难以避免的"]),
  word("reliability", "可靠性", "名词", "The quality of being dependable.", "dependability", "Engineers tested the reliability of the system.", ["可信度"]),
  word("hypothesis", "假设", "名词", "An idea used as a starting point for explanation.", "theory", "The scientist tested her hypothesis.", ["假说"]),
  word("comprehensive", "全面的", "形容词", "Including many details and covering everything important.", "thorough", "They wrote a comprehensive report.", ["综合的", "详尽的"]),
  word("emphasize", "强调", "动词", "To give special importance to something.", "stress", "The coach emphasized teamwork.", ["着重指出", "突出"]),
  word("derive", "得出", "动词", "To obtain something from a source.", "obtain", "We can derive meaning from context.", ["推导出", "推得"]),
  word("ethical", "道德的", "形容词", "Morally right and acceptable.", "moral", "Doctors face ethical decisions every day.", ["合乎伦理的", "伦理上的"]),
  word("advocate", "提倡", "动词", "To publicly support an idea or plan.", "support", "Many teachers advocate active learning.", ["主张", "倡导"]),
  word("regulate", "规范", "动词", "To control something by rules.", "control", "Laws regulate food safety.", ["监管", "调节"]),
  word("objective", "目标", "名词", "Something you are trying to achieve.", "goal", "Our objective is to reduce waste.", ["目的"]),
  word("precisely", "精确地", "副词", "In a very exact way.", "exactly", "Please explain the rule precisely.", ["准确地"]),
  word("theory", "理论", "名词", "A set of ideas intended to explain something.", "principle", "This theory changed modern science.", ["学说"])
];

const easyWordExpansion = [
  word("desk", "书桌", "名词", "A table used for reading or writing.", "table", "My notebook is on the desk.", ["桌子", "课桌", "写字桌"]),
  word("pen", "钢笔", "名词", "A tool used for writing.", "marker", "He writes with a blue pen.", ["笔", "水笔", "签字笔"]),
  word("pencil", "铅笔", "名词", "A writing tool with graphite inside.", "writing tool", "Use a pencil for the drawing.", ["笔", "木铅笔"]),
  word("bag", "包", "名词", "A container used to carry things.", "sack", "She puts books in her bag.", ["书包", "背包", "包包"]),
  word("bed", "床", "名词", "A piece of furniture for sleeping.", "sleeping place", "The bed is soft and warm.", ["床铺"]),
  word("room", "房间", "名词", "A part of a building enclosed by walls.", "chamber", "My room is clean.", ["屋子", "房间里"]),
  word("kitchen", "厨房", "名词", "A room where people cook food.", "cookroom", "Mom is cooking in the kitchen.", ["厨房间"]),
  word("bathroom", "浴室", "名词", "A room for washing or using the toilet.", "washroom", "The bathroom is upstairs.", ["洗手间", "卫生间", "厕所"]),
  word("city", "城市", "名词", "A large town where many people live.", "metropolis", "Shanghai is a big city.", ["城里", "都市"]),
  word("village", "村庄", "名词", "A small place where people live.", "settlement", "My grandparents live in a village.", ["村子", "乡村"]),
  word("park", "公园", "名词", "A public area with grass and trees.", "garden", "We walk in the park after dinner.", ["园区"]),
  word("store", "商店", "名词", "A place where people buy things.", "shop", "The store closes at nine.", ["店", "店铺", "小店"]),
  word("market", "市场", "名词", "A place where people buy and sell goods.", "bazaar", "Fresh vegetables are sold at the market.", ["集市", "菜市场"]),
  word("doctor", "医生", "名词", "A person trained to treat illness.", "physician", "The doctor checked my throat.", ["大夫", "医师"]),
  word("nurse", "护士", "名词", "A person who cares for sick people.", "caregiver", "The nurse helped the patient.", ["护理人员"]),
  word("police", "警察", "名词", "People whose job is to keep public order.", "officer", "The police helped us cross the road.", ["警员", "民警"]),
  word("money", "钱", "名词", "Coins or notes used to buy things.", "cash", "I saved money for a new book.", ["金钱", "现金", "钞票"]),
  word("time", "时间", "名词", "What is measured in seconds, minutes, and hours.", "duration", "We need more time.", ["时候", "时刻"]),
  word("day", "白天", "名词", "The time when there is daylight.", "daytime", "It is warm during the day.", ["一天", "日子"]),
  word("week", "星期", "名词", "A period of seven days.", "seven days", "We have a test next week.", ["周", "一周"]),
  word("month", "月份", "名词", "One of the twelve parts of a year.", "calendar month", "My birthday is this month.", ["月", "一个月"]),
  word("year", "年", "名词", "A period of twelve months.", "calendar year", "This year is important to me.", ["年份", "一年"]),
  word("color", "颜色", "名词", "The appearance of things such as red or blue.", "hue", "What color is your bag?", ["色彩", "色"]),
  word("red", "红色", "形容词", "Having the color of blood.", "crimson", "She wears a red coat.", ["红", "红的"]),
  word("blue", "蓝色", "形容词", "Having the color of the sky.", "azure", "The sky is blue.", ["蓝", "蓝的"]),
  word("green", "绿色", "形容词", "Having the color of grass.", "emerald", "The leaves are green.", ["绿", "绿的"]),
  word("black", "黑色", "形容词", "Having the darkest color.", "dark", "He bought a black hat.", ["黑", "黑的"]),
  word("white", "白色", "形容词", "Having the color of snow.", "pale", "The wall is white.", ["白", "白的"]),
  word("open", "打开", "动词", "To move something so it is not closed.", "unlock", "Please open the door.", ["开启", "开"]),
  word("close", "关闭", "动词", "To shut something.", "shut", "Close the window before sleep.", ["关上", "关"]),
  word("walk", "走路", "动词", "To move on foot.", "go on foot", "We walk to school together.", ["走", "步行"]),
  word("run", "跑步", "动词", "To move quickly on foot.", "sprint", "They run in the playground.", ["跑", "奔跑"]),
  word("jump", "跳", "动词", "To push your body off the ground.", "leap", "The children jump over the rope.", ["跳跃"]),
  word("play", "玩", "动词", "To do an activity for fun.", "have fun", "They play games after class.", ["玩耍", "打游戏"]),
  word("sleep", "睡觉", "动词", "To rest with your eyes closed.", "rest", "Babies sleep a lot.", ["睡", "入睡"]),
  word("buy", "买", "动词", "To get something by paying money.", "purchase", "I will buy a new pen.", ["购买"]),
  word("sell", "卖", "动词", "To give something for money.", "trade", "They sell fruit in the market.", ["出售"]),
  word("give", "给", "动词", "To hand something to someone.", "offer", "Please give me the book.", ["给予", "交给"]),
  word("take", "拿", "动词", "To get or carry something.", "carry", "Take an umbrella with you.", ["拿走", "带走", "取"]),
  word("help", "帮助", "动词", "To make it easier for someone to do something.", "assist", "Can you help me?", ["帮忙", "帮"])
];

const mediumWordExpansion = [
  word("organize", "组织", "动词", "To arrange things in a planned way.", "arrange", "She organized the school event.", ["安排", "整理", "筹划"]),
  word("explain", "解释", "动词", "To make something clear or easy to understand.", "clarify", "Please explain the answer.", ["说明", "讲解", "说清楚"]),
  word("describe", "描述", "动词", "To say what something is like.", "portray", "Can you describe the picture?", ["描写", "形容", "说明"]),
  word("suggest", "建议", "动词", "To give an idea about what someone should do.", "advise", "I suggest taking a short break.", ["提议", "推荐", "提出建议"]),
  word("accept", "接受", "动词", "To agree to receive or allow something.", "receive", "She accepted the invitation.", ["接纳", "同意", "收下"]),
  word("refuse", "拒绝", "动词", "To say no to something.", "reject", "He refused the offer politely.", ["回绝", "不接受", "拒收"]),
  word("invite", "邀请", "动词", "To ask someone to come somewhere.", "ask over", "They invite us to dinner.", ["请", "邀约"]),
  word("celebrate", "庆祝", "动词", "To do something special for a happy event.", "mark", "We celebrate the festival together.", ["庆贺", "过节", "庆祝一下"]),
  word("connect", "连接", "动词", "To join two or more things.", "link", "This bridge connects two towns.", ["联系", "连上", "接通"]),
  word("control", "控制", "动词", "To direct or limit something.", "manage", "Try to control your speed.", ["掌控", "管住", "操控"]),
  word("imagine", "想象", "动词", "To form a picture in your mind.", "picture", "Imagine a world without phones.", ["设想", "脑补", "幻想"]),
  word("notice", "注意到", "动词", "To become aware of something.", "observe", "Did you notice the mistake?", ["察觉", "发现", "看到"]),
  word("realize", "意识到", "动词", "To understand something clearly.", "understand", "I realized my mistake later.", ["认识到", "明白", "发现"]),
  word("remember", "记得", "动词", "To keep something in your mind.", "recall", "Remember to bring your book.", ["记住", "想起"]),
  word("forget", "忘记", "动词", "To fail to remember something.", "overlook", "Don't forget your homework.", ["忘了", "遗忘"]),
  word("continue", "继续", "动词", "To keep doing something.", "keep going", "The class will continue after lunch.", ["接着", "持续", "延续"]),
  word("avoid", "避免", "动词", "To stay away from something bad.", "prevent", "Avoid making the same mistake.", ["避开", "防止", "不要"]),
  word("allow", "允许", "动词", "To let someone do something.", "permit", "The teacher allowed us to leave early.", ["许可", "准许", "让"]),
  word("require", "需要", "动词", "To need something.", "need", "This task requires patience.", ["要求", "必须要", "需要有"]),
  word("depend", "依赖", "动词", "To need someone or something for support.", "rely", "Children depend on adults.", ["依靠", "取决于", "靠"]),
  word("choice", "选择", "名词", "An act of choosing between options.", "option", "You made a good choice.", ["选项", "决定", "抉择"]),
  word("reason", "原因", "名词", "Why something happens or is done.", "cause", "What is the reason for the delay?", ["理由", "缘由", "起因"]),
  word("result", "结果", "名词", "Something that happens because of an action.", "outcome", "The result was better than expected.", ["后果", "成果", "结局"]),
  word("purpose", "目的", "名词", "The reason for doing something.", "aim", "The purpose of the game is practice.", ["目标", "用意", "意图"]),
  word("process", "过程", "名词", "A series of actions or changes.", "procedure", "Learning is a long process.", ["流程", "步骤", "进程"]),
  word("progress", "进步", "名词", "Improvement or movement toward a goal.", "advance", "You made great progress this week.", ["进展", "提升", "推进"]),
  word("ability", "能力", "名词", "The power or skill to do something.", "skill", "Practice improves ability.", ["本领", "技能", "实力"]),
  word("attention", "注意力", "名词", "Careful thought or focus.", "focus", "Pay attention to the pronunciation.", ["专注力", "关注", "留意"]),
  word("confidence", "信心", "名词", "Belief in yourself or others.", "self-belief", "Success builds confidence.", ["自信", "底气", "把握"]),
  word("difficulty", "困难", "名词", "A problem or something hard to do.", "trouble", "We solved the difficulty together.", ["难处", "难点", "问题"]),
  word("decision", "决定", "名词", "A choice that you make.", "choice", "It was a difficult decision.", ["抉择", "选择", "决策"]),
  word("direction", "方向", "名词", "The way something moves or points.", "way", "Go in the opposite direction.", ["方位", "走向", "方向感"]),
  word("advantage", "优势", "名词", "Something that helps you succeed.", "benefit", "Speed is an advantage in this game.", ["好处", "优点", "有利条件"]),
  word("disadvantage", "劣势", "名词", "Something that makes success harder.", "drawback", "The plan has one disadvantage.", ["缺点", "不利条件", "短板"]),
  word("condition", "条件", "名词", "Something needed or affecting a situation.", "requirement", "Good light is an important condition.", ["情况", "状态", "前提"]),
  word("influence", "影响", "名词", "The power to affect someone or something.", "effect", "Friends can have a strong influence.", ["作用", "影响力", "带动"]),
  word("benefit", "好处", "名词", "A helpful or good effect.", "advantage", "Exercise has many benefits.", ["益处", "利益", "优点"]),
  word("self-confidence", "自信", "名词", "A feeling that you can do something well.", "belief", "Speaking more gives you self-confidence.", ["信心", "底气", "把握"]),
  word("active", "积极的", "形容词", "Doing things with energy and interest.", "energetic", "She is active in class.", ["主动的", "活跃的", "积极"]),
  word("patient", "有耐心的", "形容词", "Able to wait calmly.", "tolerant", "A patient teacher helps students learn.", ["耐心", "耐心的", "能等的"])
];

const hardWordExpansion = [
  word("ambiguous", "模糊的", "形容词", "Having more than one possible meaning.", "unclear", "The message was ambiguous.", ["含糊的", "不明确的", "暧昧的"]),
  word("abstract", "抽象的", "形容词", "Existing as an idea rather than a physical thing.", "conceptual", "Freedom is an abstract idea.", ["抽象", "概念性的"]),
  word("adequate", "足够的", "形容词", "Enough for a particular purpose.", "sufficient", "We have adequate time to finish.", ["充足的", "够用的", "充分的"]),
  word("alternative", "替代方案", "名词", "Another choice or possibility.", "option", "We need an alternative plan.", ["备选方案", "替代选择", "另一种选择"]),
  word("anticipate", "预料", "动词", "To expect something to happen.", "expect", "We anticipate some problems.", ["预测", "预期", "料到"]),
  word("apparent", "明显的", "形容词", "Easy to see or understand.", "obvious", "The reason became apparent later.", ["显然的", "看得出来的", "清楚的"]),
  word("approach", "方法", "名词", "A way of dealing with something.", "method", "This approach works well.", ["方式", "办法", "思路"]),
  word("assert", "断言", "动词", "To state something firmly.", "claim", "He asserted that the result was correct.", ["声称", "坚称", "明确表示"]),
  word("bias", "偏见", "名词", "An unfair preference or opinion.", "prejudice", "Data can contain hidden bias.", ["偏向", "成见", "偏差"]),
  word("capacity", "能力", "名词", "The ability or amount something can hold.", "ability", "The system has limited capacity.", ["容量", "承载力", "本事"]),
  word("coherent", "连贯的", "形容词", "Clear and logically connected.", "logical", "Her answer was coherent.", ["有条理的", "清楚连贯的", "一致的"]),
  word("constraint", "限制", "名词", "Something that limits what you can do.", "limit", "Time is our biggest constraint.", ["约束", "限制条件", "束缚"]),
  word("contradict", "反驳", "动词", "To say the opposite of something.", "oppose", "The facts contradict his story.", ["矛盾", "否定", "与...相反"]),
  word("criteria", "标准", "名词", "Rules used to judge or decide something.", "standards", "The project must meet these criteria.", ["准则", "评判标准", "条件"]),
  word("deduce", "推断", "动词", "To reach an answer by reasoning.", "infer", "We can deduce the answer from clues.", ["推理", "推导", "判断出"]),
  word("dimension", "维度", "名词", "An aspect or measurement of something.", "aspect", "The issue has a social dimension.", ["方面", "层面", "尺度"]),
  word("distinguish", "区分", "动词", "To recognize differences between things.", "differentiate", "Can you distinguish these two sounds?", ["分辨", "辨别", "区别"]),
  word("empirical", "经验的", "形容词", "Based on observation or experiment.", "observed", "The study needs empirical evidence.", ["实证的", "基于经验的", "观察得来的"]),
  word("entity", "实体", "名词", "Something that exists as a separate thing.", "being", "A company is a legal entity.", ["个体", "存在物", "单位"]),
  word("exceed", "超过", "动词", "To be greater than a number or limit.", "surpass", "The cost may exceed our budget.", ["超出", "超越", "超过限制"]),
  word("explicit", "明确的", "形容词", "Stated clearly and directly.", "clear", "The instructions were explicit.", ["清楚的", "直白的", "明说的"]),
  word("implicit", "含蓄的", "形容词", "Suggested but not directly stated.", "implied", "There was an implicit warning.", ["隐含的", "暗含的", "不明说的"]),
  word("infrastructure", "基础设施", "名词", "Basic systems needed for a place or organization.", "basic systems", "Good infrastructure supports growth.", ["基建", "基础建设", "设施"]),
  word("integrate", "整合", "动词", "To combine things into a whole.", "combine", "We integrate new ideas into the plan.", ["融合", "合并", "结合"]),
  word("justify", "证明合理", "动词", "To show that something is right or reasonable.", "defend", "You need to justify your answer.", ["辩解", "说明理由", "证明有道理"]),
  word("legitimate", "合法的", "形容词", "Allowed by law or accepted as reasonable.", "valid", "That is a legitimate concern.", ["正当的", "合理的", "合规的"]),
  word("marginal", "边缘的", "形容词", "Small or not very important.", "minor", "The change had only a marginal effect.", ["微小的", "不重要的", "边际的"]),
  word("mechanism", "机制", "名词", "A system or process that makes something work.", "process", "The mechanism is still unclear.", ["原理", "运行方式", "机制原理"]),
  word("paradigm", "范式", "名词", "A typical model or pattern.", "model", "This discovery changed the scientific paradigm.", ["模式", "典范", "框架"]),
  word("plausible", "合理的", "形容词", "Seeming likely to be true.", "believable", "That is a plausible explanation.", ["可信的", "说得通的", "有可能的"]),
  word("preliminary", "初步的", "形容词", "Done before the main action.", "initial", "These are preliminary results.", ["初始的", "预备的", "前期的"]),
  word("proportion", "比例", "名词", "A part compared with the whole.", "ratio", "A large proportion of students agreed.", ["比重", "份额", "占比"]),
  word("rational", "理性的", "形容词", "Based on reason rather than emotion.", "reasonable", "We need a rational discussion.", ["合理的", "讲理的", "冷静的"]),
  word("scenario", "情景", "名词", "A possible situation or sequence of events.", "situation", "Imagine the worst-case scenario.", ["场景", "情况", "局面"]),
  word("scope", "范围", "名词", "The area or limits covered by something.", "range", "The scope of the project is clear.", ["界限", "覆盖范围", "规模"]),
  word("simulate", "模拟", "动词", "To copy the conditions of something.", "model", "The program simulates real traffic.", ["仿真", "演示", "模拟运行"]),
  word("subtle", "微妙的", "形容词", "Not obvious and hard to notice.", "delicate", "There is a subtle difference.", ["细微的", "不明显的", "含蓄的"]),
  word("substitute", "替代", "动词", "To use one thing instead of another.", "replace", "You can substitute milk with water.", ["代替", "替换", "顶替"]),
  word("valid", "有效的", "形容词", "Based on truth or accepted rules.", "sound", "Your point is valid.", ["合理的", "成立的", "有根据的"]),
  word("viable", "可行的", "形容词", "Able to work successfully.", "workable", "This is a viable solution.", ["行得通的", "能实现的", "可实施的"])
];

export const difficultyConfig = {
  easy: {
    label: "简单",
    speed: 28,
    hp: 5,
    points: 10,
    words: [...easyWords, ...easyWordExpansion]
  },
  medium: {
    label: "中等",
    speed: 34,
    hp: 5,
    points: 18,
    words: [...mediumWords, ...mediumWordExpansion]
  },
  hard: {
    label: "困难",
    speed: 34,
    hp: 4,
    points: 30,
    words: [...hardWords, ...hardWordExpansion]
  }
};

export const shopItems = [
  {
    id: "skipPack",
    name: "秒杀子弹补给",
    cost: 60,
    desc: "下局开场直接获得 3 发秒杀子弹。",
    short: "秒杀子弹 +3"
  },
  {
    id: "shieldBoost",
    name: "基地护盾",
    cost: 80,
    desc: "下局基地血量额外 +1。",
    short: "基地血量 +1"
  },
  {
    id: "slowChip",
    name: "减速芯片",
    cost: 90,
    desc: "下局怪物移动速度降低 15%。",
    short: "怪物减速 15%"
  },
  {
    id: "scoreBoost",
    name: "积分增幅器",
    cost: 110,
    desc: "下局击杀积分提升至 1.5 倍。",
    short: "击杀积分 x1.5"
  },
  {
    id: "freezeBomb",
    name: "冻结脉冲",
    cost: 70,
    desc: "战斗中主动使用，冻结所有场上怪物 3 秒。",
    short: "全场冻结 3 秒"
  },
  {
    id: "clearBomb",
    name: "清屏炸弹",
    cost: 130,
    desc: "战斗中主动使用，直接清除当前场上的全部怪物并获得积分。",
    short: "清除场上怪物"
  }
];

export function createEmptyInventory() {
  return {
    skipPack: 0,
    shieldBoost: 0,
    slowChip: 0,
    scoreBoost: 0,
    freezeBomb: 0,
    clearBomb: 0
  };
}
